name: mid_devon
description: Mid Devon planning applications (idox)
stealthy: True
pipeline:
  init:
    method: seed
    params:
      urls:
        - https://planning.middevon.gov.uk/online-applications/applicationDetails.do?keyVal=PMYX2RKS07T00&activeTab=summary
        - https://planning.middevon.gov.uk/online-applications/applicationDetails.do?keyVal=PLU4CJKS07T00&activeTab=summary
        - https://planning.middevon.gov.uk/online-applications/applicationDetails.do?keyVal=PVYSTZKS07T00&activeTab=summary
        - https://planning.middevon.gov.uk/online-applications/applicationDetails.do?keyVal=PEOIF9KS07T00&activeTab=summary
        - https://planning.middevon.gov.uk/online-applications/applicationDetails.do?keyVal=PQRRVMKS02X00&activeTab=summary
        - https://planning.middevon.gov.uk/online-applications/applicationDetails.do?keyVal=QUQDIKKS07T00&activeTab=summary
        - https://planning.middevon.gov.uk/online-applications/applicationDetails.do?keyVal=PR4TFOKS07T00&activeTab=summary
        - https://planning.middevon.gov.uk/online-applications/applicationDetails.do?keyVal=QFRM4KKS07T00&activeTab=summary
        - https://planning.middevon.gov.uk/online-applications/applicationDetails.do?keyVal=PWBPYZKS07T00&activeTab=summary
        - https://planning.middevon.gov.uk/online-applications/applicationDetails.do?keyVal=Q5A1Z9KS04G00&activeTab=summary
        - https://planning.middevon.gov.uk/online-applications/applicationDetails.do?keyVal=PVWQ8YKS07T00&activeTab=summary
        - https://planning.middevon.gov.uk/online-applications/applicationDetails.do?activeTab=summary&keyVal=QSXYTMKS07T00
        - https://planning.middevon.gov.uk/online-applications/applicationDetails.do?keyVal=Q070W3KS0IY00&activeTab=summary
        - https://planning.middevon.gov.uk/online-applications/applicationDetails.do?activeTab=summary&keyVal=PPZWNPKS07T00
        - https://planning.middevon.gov.uk/online-applications/applicationDetails.do?keyVal=PEVXR2KS05K00&activeTab=summary
        - https://planning.middevon.gov.uk/online-applications/applicationDetails.do?keyVal=QKPHNRKS05K00&activeTab=summary
        - https://planning.middevon.gov.uk/online-applications/applicationDetails.do?keyVal=QKPH1NKS05K00&activeTab=summary
        - https://planning.middevon.gov.uk/online-applications/applicationDetails.do?keyVal=Q5ZUZMKS03J00&activeTab=summary
        - https://planning.middevon.gov.uk/online-applications/applicationDetails.do?keyVal=QEU5VBKS07T00&activeTab=summary
        - https://planning.middevon.gov.uk/online-applications/applicationDetails.do?keyVal=QE9YJSKS04G00&activeTab=summary
        - https://planning.middevon.gov.uk/online-applications/applicationDetails.do?keyVal=PTATXBKS03J00&activeTab=summary
    handle:
      pass: seed
  seed:
    method: padocs.idox:docs_url
    handle:
      pass: fetch
  fetch:
    method: fetch
    handle:
      pass: parse
  parse:
    method: padocs.idox:parse
    params:
      link_index: 5
      description_index: 4
    handle:
      pass: fetch_doc
  fetch_doc:
    method: fetch
    handle:
      pass: store_doc
  store_doc:
    method: aleph_emit_document
    handle:
      pass: process
  process:
    method: padocs:aleph_process
    handle:
      pass: store
  store:
    method: db
    params:
      table: mid_devon_documents
      unique:
        - aleph_document_id
aggregator:
  method: padocs:export
  params:
    table: mid_devon_documents