name: mid_devon
description: Mid Devon planning applications (idox)
stealthy: True
pipeline:
  init:
    method: seed
    params:
      urls:
        - https://planning.middevon.gov.uk/online-applications/applicationDetails.do?keyVal=PG0P3NKS07T00&activeTab=summary
        - https://planning.middevon.gov.uk/online-applications/applicationDetails.do?keyVal=PIY2CCKS07T00&activeTab=summary
        - https://planning.middevon.gov.uk/online-applications/applicationDetails.do?keyVal=PNL98UKS03J00&activeTab=summary
        - https://planning.middevon.gov.uk/online-applications/applicationDetails.do?keyVal=PNMPLSKS07T00&activeTab=summary
        - https://planning.middevon.gov.uk/online-applications/applicationDetails.do?keyVal=PSMKFMKS07T00&activeTab=summary
        - https://planning.middevon.gov.uk/online-applications/applicationDetails.do?keyVal=PTR0S9KS07T00&activeTab=summary
        - https://planning.middevon.gov.uk/online-applications/applicationDetails.do?keyVal=PVZ3P4KS03J00&activeTab=summary
        - https://planning.middevon.gov.uk/online-applications/applicationDetails.do?keyVal=PWJDTEKS03J01&activeTab=summary
        - https://planning.middevon.gov.uk/online-applications/applicationDetails.do?keyVal=PZ7JXSKS07T00&activeTab=summary
        - https://planning.middevon.gov.uk/online-applications/applicationDetails.do?keyVal=Q4GIKOKS05K00&activeTab=summary
        - https://planning.middevon.gov.uk/online-applications/applicationDetails.do?keyVal=QPUIC6KS07T00&activeTab=summary
        - https://planning.middevon.gov.uk/online-applications/applicationDetails.do?keyVal=QQIW3VKS04G00&activeTab=summary
    handle:
      pass: seed
  seed:
    method: padocs.idox:docs_url
    handle:
      pass: fetch
  fetch:
    method: fetch
    handle:
      pass: parse
  parse:
    method: padocs.idox:parse
    handle:
      pass: fetch_doc
  fetch_doc:
    method: fetch
    handle:
      pass: store_doc
  store_doc:
    method: aleph_emit_document
    handle:
      pass: process
  process:
    method: padocs:aleph_process
    handle:
      pass: store
  store:
    method: db
    params:
      table: mid_devon_documents
      unique:
        - aleph_document_id
aggregator:
  method: padocs:export
  params:
    table: mid_devon_documents