version: "2"

services:
  datastore:
    image: postgres:11.4
    volumes:
      - "./build/datastore:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: datastore
      POSTGRES_PASSWORD: datastore

  redis:
    image: redis:alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./build/redis-data:/data

  shell:
    build: .
    command: /bin/bash
    links:
      - redis
      - datastore
    env_file:
      - config.env
    environment:
      MEMORIOUS_DEBUG: 'true'
      PYTHONPATH: '/crawlers/src'
    volumes:
      - "./build/data:/data"
      - "./config:/crawlers/config"
      - "./src:/crawlers/src"
    tmpfs:
      - "/tmp"
